# --- Configuration ---
$appListFile = "C:\MuleProjects\app-list.txt" 
$baseSshUrl = 'git@ssh.dev.azure.com:v3/YourOrg/YourProject/' 
$rootWorkDir = "C:\MuleTempBuilds"
$consolidatedCsv = Join-Path $rootWorkDir "Consolidated_Coverage_Report.csv"

# --- Initialization ---
if (!(Test-Path $rootWorkDir)) { 
    New-Item -ItemType Directory -Path $rootWorkDir -Force | Out-Null 
}

# Clear old report and set Headers
# Repository: App Name | Component: Specific Test or Flow | Status: Pass/Fail | Coverage: App Total %
"Repository,Component,Status,Coverage,Details,Timestamp" | Out-File $consolidatedCsv -Encoding utf8 -Force

if (!(Test-Path $appListFile)) {
    Write-Host "Error: $appListFile not found!" -ForegroundColor Red
    return
}

# Filter out empty lines from the app list
$repos = Get-Content $appListFile | Where-Object { ![string]::IsNullOrWhiteSpace($_) }

foreach ($repoName in $repos) {
    $repoName = $repoName.Trim()
    $targetPath = Join-Path $rootWorkDir $repoName
    Write-Host "`n>>> Starting: $repoName" -ForegroundColor Cyan

    try {
        # 1. Git Logic: Update if exists, Clone if new
        if (Test-Path $targetPath) {
            Write-Host "Updating existing repo..." -ForegroundColor Gray
            Set-Location $targetPath
            git reset --hard; git checkout dev; git fetch --all; git pull origin dev --quiet
        } else {
            Write-Host "Cloning fresh dev branch..." -ForegroundColor Gray
            Set-Location $rootWorkDir
            git clone --branch dev --single-branch "$baseSshUrl$repoName" $repoName --quiet
            Set-Location $targetPath
        }

        # 2. Execute Maven with explicit coverage-report goal (per your Parent POM)
        Write-Host "Building and generating MUnit reports..." -ForegroundColor Blue
        # Note: We escape colons for PowerShell using the backtick (`)
        $mvnOutput = mvn clean test com.mulesoft.munit.tools`:munit-maven-plugin`:coverage-report `
            "-DsecureKey=s3cr3t" `
            "-Denv=dev" `
            "-DargLine=-DsecureKey=s3cr3t -Denv=dev" `
            "-Dmaven.test.failure.ignore=true" 2>&1

        # 3. Extract Overall Application Coverage
        # Looking for summary.html generated by the coverage-report goal
        $reportPath = "$targetPath\target\site\munit\coverage\summary.html"
        $overallCoverage = "N/A"
        if (Test-Path $reportPath) {
            $html = Get-Content $reportPath -Raw
            if ($html -match '<span>(\d+(?:\.\d+)?)%</span>') { 
                $overallCoverage = $matches[1] + "%" 
            }
        }

        # 4. Parse Individual Test Failures (Multi-row logic)
        $testReportDir = "$targetPath\target\munit-reports"
        $failureCount = 0

        if (Test-Path $testReportDir) {
            $xmlFiles = Get-ChildItem "$testReportDir\*.xml"
            foreach ($file in $xmlFiles) {
                [xml]$xmlData = Get-Content $file.FullName
                foreach ($testCase in $xmlData.testsuite.testcase) {
                    if ($testCase.failure -or $testCase.error) {
                        $failureCount++
                        $tName = $testCase.name
                        # Clean error message for CSV compatibility
                        $errMsg = ($testCase.failure.Message -replace '[,"]',' ')
                        "$repoName,$tName,FAILED,$overallCoverage,$errMsg,$(Get-Date)" | Out-File $consolidatedCsv -Append
                    }
                }
            }
        }

        # 5. Final Row Logging
        if ($mvnOutput -match "BUILD FAILURE" -and $failureCount -eq 0) {
            # Build failed before tests could run (e.g., Dependency/Parent POM issue)
            $buildErr = ($mvnOutput -match "\[ERROR\]" | Select-Object -First 1) -replace '[,"]',' '
            "$repoName,BuildSystem,BUILD_ERROR,$overallCoverage,$buildErr,$(Get-Date)" | Out-File $consolidatedCsv -Append
        } elseif ($failureCount -eq 0) {
            # Total Success
            "$repoName,All Suites,PASSED,$overallCoverage,Success,$(Get-Date)" | Out-File $consolidatedCsv -Append
        }

        Write-Host "Completed $repoName with Coverage: $overallCoverage" -ForegroundColor Green

    } catch {
        Write-Host "Script Error on $repoName : $($_.Exception.Message)" -ForegroundColor Red
        "$repoName,System,SCRIPT_ERROR,N/A,$($_.Exception.Message -replace '[,"]',' '),$(Get-Date)" | Out-File $consolidatedCsv -Append
    }
}

Write-Host "`nAll tasks finished. Check the consolidated report at:" -ForegroundColor Yellow
Write-Host $consolidatedCsv -ForegroundColor White
